### ISSUE TITLE
损失变好而肺部配准结果越差。

### ISSUE THREAD

**Issue by ZZC9965** [xi-jia/LKU-Net#9]
您好，我将您的代码修改为肺配准，NCC损失窗口调整为20，数据集使用NLST，当我遇到了一些问题，损失确实再向-1靠近，但配准效果却越来越差，您在肺部配准时遇到这个问题了嘛，或者是否可以分享一下您的肺部配准代码。

**Comment by xi-jia** [comment]
抱歉前段时间放假。
代码和这个一样，就是data loader换了而已。
不知道您说的配准效果却越来越差是以什么衡量的，能否说一下你的训练和测试的损失函数？
